USE [master]
GO

/****** Object:  Database [Exam-Yusupov]    Script Date: 08.04.2024 14:15:37 ******/
DROP DATABASE [Exam-Yusupov]
GO

/****** Object:  Database [Exam-Yusupov]    Script Date: 08.04.2024 14:15:37 ******/
CREATE DATABASE [Exam-Yusupov]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Exam-Yusupov', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.IS2012\MSSQL\DATA\Exam-Yusupov.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Exam-Yusupov_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.IS2012\MSSQL\DATA\Exam-Yusupov_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Exam-Yusupov].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Exam-Yusupov] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Exam-Yusupov] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Exam-Yusupov] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Exam-Yusupov] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Exam-Yusupov] SET ARITHABORT OFF 
GO

ALTER DATABASE [Exam-Yusupov] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Exam-Yusupov] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Exam-Yusupov] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Exam-Yusupov] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Exam-Yusupov] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Exam-Yusupov] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Exam-Yusupov] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Exam-Yusupov] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Exam-Yusupov] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Exam-Yusupov] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Exam-Yusupov] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Exam-Yusupov] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Exam-Yusupov] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Exam-Yusupov] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Exam-Yusupov] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Exam-Yusupov] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Exam-Yusupov] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Exam-Yusupov] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Exam-Yusupov] SET  MULTI_USER 
GO

ALTER DATABASE [Exam-Yusupov] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Exam-Yusupov] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Exam-Yusupov] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Exam-Yusupov] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Exam-Yusupov] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Exam-Yusupov] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Exam-Yusupov] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Exam-Yusupov] SET  READ_WRITE 
GO

